spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artistdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

webclient:
  base-url: https://api.discogs.com
  timeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
    instances:
      discogsApi:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2000ms
    instances:
      discogsApi:
        base-config: default

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.clara: DEBUG
